WINDOW_TOP_LEFT = 'images/window_top_left.png'
WINDOW_WIDTH = 792
WINDOW_HEIGHT = 577

TABLE_TOP_LEFT = 'images/table_top_left.png'
TABLE_WIDTH = 792
TABLE_HEIGHT = 547

ACTION_HEIGHT = 41
ACTION_BET = 'images/action_bet.png'
ACTION_CALL = 'images/action_call.png'
ACTION_CHECK = 'images/action_check.png'
ACTION_FOLD = 'images/action_fold.png'
ACTION_RAISE_TO = 'images/action_raise_to.png'

CARD_ANCHOR = 'images/card_anchor.png'
CARD_COLOR_C = 'images/card_color_c.png'
CARD_COLOR_D = 'images/card_color_d.png'
CARD_COLOR_H = 'images/card_color_h.png'
CARD_COLOR_S = 'images/card_color_s.png'
CARD_VALUE_X_OFFSET = -16
CARD_VALUE_Y_OFFSET = 4
CARD_VALUE_WIDTH = 13
CARD_VALUE_HEIGHT = 15
CARD_VALUE_A = ('images/card_value_a.png', 'images/card_value_a_r.png')
CARD_VALUE_2 = ('images/card_value_2.png', 'images/card_value_2_r.png')
CARD_VALUE_3 = ('images/card_value_3.png', 'images/card_value_3_r.png')
CARD_VALUE_4 = ('images/card_value_4.png', 'images/card_value_4_r.png')
CARD_VALUE_5 = ('images/card_value_5.png', 'images/card_value_5_r.png')
CARD_VALUE_6 = ('images/card_value_6.png', 'images/card_value_6_r.png')
CARD_VALUE_7 = ('images/card_value_7.png', 'images/card_value_7_r.png')
CARD_VALUE_8 = ('images/card_value_8.png', 'images/card_value_8_r.png')
CARD_VALUE_9 = ('images/card_value_9.png', 'images/card_value_9_r.png')
CARD_VALUE_10 = ('images/card_value_10.png', 'images/card_value_10_r.png')
CARD_VALUE_J = ('images/card_value_j.png', 'images/card_value_j_r.png')
CARD_VALUE_Q = ('images/card_value_q.png', 'images/card_value_q_r.png')
CARD_VALUE_K = ('images/card_value_k.png', 'images/card_value_k_r.png')
CARD_COLOR_X_OFFSET = -17
CARD_COLOR_Y_OFFSET = 19
CARD_COLOR_WIDTH = 16
CARD_COLOR_HEIGHT = 16
HAND_CARDS_Y_OFFSET = 300
